#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorA,          rightM,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftM,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float angleTarget = 180;//degrees

float dt=50;

//the constants for the PID trerms
float kp = 5;
//float ki = ;
//float kd = ;

float error = 0.0, prevError = 0.0;
float proportional, derivative, integral; //error terms
int output;
int currentAngle;

task PIDController(){
		while(true){
	sleep(dt);
		currentAngle = getGyroDegrees(gyro);
		error = angleTarget-currentAngle;
	  //currentAngle = .... (update current angle from Gyro)
		//error = ?;
		proportional = kp*error;
		output =   proportional;

	}
}
//answer for step 1 :-
//dt is the change in time and is used to sleep the PID controller whilst it is looping
//the error is the current difference in the current angle and the desired angle
void init(){
	output = 0;
	resetGyro(gyro);
	setMotorBrakeMode(motorA, motorCoast);
	setMotorSpeed(motorA, 0);
	setMotorBrakeMode(motorC, motorCoast);
	setMotorSpeed(motorC, 0);
}

void display(){
	displayTextLine(0, "dt : %f", dt);
	displayTextLine(1, "angle target : %f",angleTarget);
	displayTextLine(2, "angle : %2f", currentAngle);
	displayTextLine(3, "error : %2f", error);
	displayTextLine(4, "PID output: %d", output);
	displayTextLine(10, "kp = %f", kp);
}

task main()
{
	init();
	startTask(PIDController);
	sleep(3000);
	while(true){
		setMotorSpeed(leftM, (output));
		setMotorSpeed(rightM, (-output));
		display();
	}
	stopTask(PIDController);
}
PID
