#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     lightSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

long leftPos,rightPos;

task main(){

	while (true){
  	leftPos = getMotorEncoder(leftMotor);
 		rightPos = getMotorEncoder(rightMotor);

  	setMotorTarget(leftMotor, leftPos+828,50);
  	setMotorTarget(rightMotor, rightPos+828,50);

  	waitUntilMotorStop(leftMotor);

  	leftPos = getMotorEncoder(leftMotor);
  	rightPos = getMotorEncoder(rightMotor);

  	setMotorTarget(leftMotor, leftPos+390,50);
  	setMotorSpeed(rightMotor, 0);

  	waitUntilMotorStop(leftMotor);
  }

}
