#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     lightSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

long leftPos,rightPos;

task main(){

	while (true){
    clearTimer(T1);
    
    repeatUntil(time1(T1) >= 4500){
  		setMotorSpeed(leftMotor, 20);
    	setMotorSpeed(rightMotor, 20);
  	}
    
    resetGryo(gryo);
    
    repeatUntil(getGryoDegrees(gryo) >= 90){
      setMotorSpeed(leftMotor, 20);
    	setMotorSpeed(rightMotor, 0);
    }
  }

}
