#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     lightSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

bool foundLine = false;
long r,g,b,avg,delta;
float leftSpeed = 0;
float rightSpeed = 40;
float spiralFactor = 0.5;
const float target = 480;
const float steeringMod = 0.03;
const float botSpeed = 10;
long color = 0;
bool avoidActive = false;

task wander(){

  while (!foundLine && !avoidActive){
  	displayTextLine(1, "wander");
  		color = 2;
  		sleep(300);
  		if (leftSpeed<40){
  			leftSpeed += spiralFactor;
  		}

      HTCS2readRawRGB(S3, true, r,g,b);
      avg = (r+g+b)/3;

      if (avg <=  target){
        foundLine = true;
        setMotorSpeed(leftMotor, 0);
        setMotorSpeed(rightMotor, 0);
      }
  }

}

task followLine() {
	
	while(true){
		
		while (foundLine && !avoidActive){
			
			displayTextLine(1, "follow");
			color = 0;

			rightSpeed = botSpeed + (delta * steeringMod);
			leftSpeed = botSpeed - (delta * steeringMod);

		}
		sleep(250);
	}
}


task avoid() {
	while (true){
		sleep(200);
		while(foundLine || avoidActive){	
			
				if (getUSDistance(leftSonar) < 15){
					
					displayTextLine(1, "avoid");
					avoidActive = true;
					color = 1;
					leftSpeed = botSpeed +(30 - getUSDistance(leftSonar));
					rightSpeed = botSpeed - (15- getUSDistance(leftSonar));
				}
			
				if (getUSDistance(leftSonar) > 15 && avoidActive){
					leftSpeed = botSpeed;
					rightSpeed = botSpeed+10;
				}
			
				if (avg <= target && avoidActive){
					avoidActive = false;	
				}
				
		}
	}
}

task main(){
  startTask(wander);
  startTask(followLine);
	startTask(avoid);
	
  while (true){
  	HTCS2readRawRGB(S3, true, r,g,b);
		avg = (r + g + b)/3;
		delta = target - avg;
			
		switch (color){
			case 0: 
				setLEDColor(ledGreen);
				break;
			case 1:
				setLEDColor(ledOrange);
				break;
			case 2:
				setLEDColor(ledRed);
				break;
		}
    setMotorSpeed(leftMotor, leftSpeed);
    setMotorSpeed(rightMotor, rightSpeed);

  }

}
