#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     lightSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

long botSpeed = 10;
long lSpeed = 10;
long rSpeed = 10;

bool avoidBool = false;
//bool backUp = false;
int turnCount = 0;
int i =0;
task avoid(){

while (true){

	long leftDist = getUSDistance(leftSonar);
	long rightDist = getUSDistance(rightSonar);

  //detect object and start to reverse
  if (leftDist < 15){
    avoidBool = true;
    lSpeed = 0;
    rSpeed = 0;
    sleep(1000);
  }

  if (avoidBool){
  	clearTimer(T2);
  	repeatUntil(leftDist >= 25){
  			leftDist = getUSDistance(leftSonar);
				rightDist = getUSDistance(rightSonar);
  			lSpeed = botSpeed;
				rSpeed = -botSpeed;
  		}
  		long time = time1(T2)*1.7;

  	clearTimer(T1);
		repeatUntil(time1(T1) >= 8000){
  			lSpeed = botSpeed;
				rSpeed = botSpeed;
		}
		clearTimer(T2);
		repeatUntil(time1(T2) >= time){
  			lSpeed = -botSpeed;
				rSpeed = botSpeed;
  		}
  //	repeatUntil(leftDist <= 25){
  //			lSpeed = botSpeed;
		//		rSpeed = botSpeed;
		//}

  		clearTimer(T1);
		repeatUntil(time1(T1) >= 9000){
  			lSpeed = botSpeed;
				rSpeed = botSpeed;
		}

		avoidBool = false;
		//lSpeed = 0;
		//rSpeed = 0;
	}

	//Turn away from obstacle
 // if (avoidBool && (leftDist <= 20 || rightDist <= 20)){
 //		repeatUntil(leftDist >= 20){
 // 			leftDist = getUSDistance(leftSonar);
	//			rightDist = getUSDistance(rightSonar);
 // 			lSpeed = botSpeed;
	//			rSpeed = -botSpeed;
 // 		}
	//}

	//if (avoidBool && leftDist >= 20){
	//	clearTimer(T1);
	//	repeatUntil(time1(T1) >= 2000){
 // 			lSpeed = botSpeed;
	//			rSpeed = botSpeed;
	//	}
	//}

	//Try turning back round
	if (i >= 2000){
		lSpeed = 0;
		rSpeed = 0;
		i=0;
		clearTimer(T1);
		repeatUntil(time1(T1) >= turnCount * 1000){
  			lSpeed = -botSpeed;
				rSpeed = botSpeed;
  	}
  	turnCount = 0;
  	lSpeed=botSpeed;
  	rSpeed=botSpeed;
	}

//	if (meet line){
		//avoidBool = false;
	//}

	}
}

task main(){

	startTask(avoid);

	while(true){
		long Ldist = getUSDistance(leftSonar);
		long Rdist = getUSDistance(rightSonar);
		displayTextLine(0,"Object Left: %f",Ldist);
		displayTextLine(1,"Object Right: %f",Rdist);

		if (avoidBool){
			displayTextLine(2,"Avoid: true");
		} else {
			displayTextLine(2,"Avoid: false");
		}

		setMotorSpeed(leftMotor, lSpeed);
		setMotorSpeed(rightMotor, rSpeed);
	}
}
