#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     lightSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

long botSpeed = 10;
long lSpeed = 10;
long rSpeed = 10;

bool avoidBool = false;
//bool backUp = false;

task avoid(){
int i;
int turnCount = 0;
while (true){

	long leftDist = getUSDistance(leftSonar);
	long rightDist = getUSDistance(rightSonar);

  //detect object and start to reverse
  if (leftDist < 20 || rightDist < 20 ){
    avoidBool = true;
  }

  if (leftDist < 10 || rightDist < 10){
		repeatUntil(leftDist >= 20 && rightDist >=20){
			leftDist = getUSDistance(leftSonar);
			rightDist = getUSDistance(rightSonar);
			lSpeed = -botSpeed;
			rSpeed = -botSpeed;
		}
	}

	//Turn away from obstacle
  if (avoidBool && leftDist <= 20){
 		repeatUntil(leftDist >= 20){
  		clearTimer(T1);
  		repeatUntil(time1(T1) >= 500){
  			leftDist = getUSDistance(leftSonar);
				rightDist = getUSDistance(rightSonar);
  			lSpeed = botSpeed;
				rSpeed = -botSpeed;
  		}
  		turnCount += 1;
  	}
  	i = 0;
	}

	if (avoidBool && leftDist > 20 && i <= 1500){
  			lSpeed = botSpeed;
				rSpeed = botSpeed;
				i+=1;
	}
	//Try turning back round
	if (i >= 1000){
		lSpeed = 0;
		rSpeed = 0;
		i=0;
		clearTimer(T1);
		repeatUntil(time1(T1) >= turnCount * 800){
  			lSpeed = -botSpeed;
				rSpeed = botSpeed;
  	}
  	turnCount = 0;
  	lSpeed=botSpeed;
  	rSpeed=botSpeed;
	}

	if (!avoidBool){
		lSpeed = botSpeed;
		rSpeed = botSpeed;
	}

	}
}

task main(){

	startTask(avoid);

	while(true){
		long Ldist = getUSDistance(leftSonar);
		long Rdist = getUSDistance(rightSonar);
		displayTextLine(0,"Object Left: %f",Ldist);
		displayTextLine(1,"Object Right: %f",Rdist);
		if (avoidBool){
			displayTextLine(2,"Avoid: true");
		} else {
			displayTextLine(2,"Avoid: false");
		}

		setMotorSpeed(leftMotor, lSpeed);
		setMotorSpeed(rightMotor, rSpeed);
	}
}
