#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     lightSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

bool foundLine = false;
long r,g,b,avg,avgCapped;

long lightThreshold = 1800;

float errP, errI, errD, errPrev;
float setPt = 450;
float setPtTolerance = 40;

//PID Coefficients
const float kP = 0.04;
const float kI = 0.018;
const float kD = 0.07;

const float baseSpeed = 10;
float leftSpeed = 0;
float rightSpeed = 0;
float spiralFactor = 0.5;
float timeSinceLostLine = 0;

float dt = 0;
const float sampleLength = 50;

/* Timers
	T1: Object avoidance
	T2: PID rrror monitor
	T3: Track time since lost line
*/

//Command request struct for behaviours to request motor control
typedef struct {
	float lSpeed;
	float rSpeed;
	bool broadcasting;
	string name;
} cmdRequest;

cmdRequest followCmd;
cmdRequest forageCmd;
cmdRequest avoidCmd;
cmdRequest observeCmd;

void wipeError(){
	errP = 0;
	errI = 0;
	errD = 0;
}

void tryCmd(cmdRequest cmd){
	if(cmd.broadcasting){
		leftSpeed = cmd.lSpeed;
		rightSpeed = cmd.rSpeed;
	}
}

long turnFixed(cmdRequest cmd, long angle, int dir){ //Turn by a fixed amount
	resetGyro(gyro);
	repeatUntil(getGyroDegrees(gyro) >= angle){
		cmd.lSpeed = 20 * dir;
		cmd.rSpeed = -20 * dir;
	}
	return getGyroDegrees(gyro);
}

task arbiter(){ //Behaviour arbitration
	while(true){
		tryCmd(forageCmd);
		tryCmd(followCmd);
		tryCmd(avoidCmd);
		//tryCmd(observeCmd);
		setMotorSpeed(leftMotor, leftSpeed);
		setMotorSpeed(rightMotor, rightSpeed);
	}
}

task forage(){
	forageCmd.name = "Forage";
	while(true){

		sleep(100);

		forageCmd.broadcasting = true;
		forageCmd.rSpeed = 30;

		if (leftSpeed < 30){
			forageCmd.lSpeed = leftSpeed + spiralFactor;
		}

	}
}

task follow() {
	followCmd.name = "Follow";
	while(true){

		HTCS2readRawRGB(S3, true, r,g,b);
		avg = (r + g + b)/3;

		//if(avg >= 800){
		//	avgCapped=800;
		//}
		//else{
		//	avgCapped = avg;
		//}

		errP = setPt - avg;

		followCmd.rSpeed = baseSpeed + ( (kP * errP) + (kI * errI) + (kD * errD) );
		followCmd.lSpeed = baseSpeed - ( (kP * errP) + (kI * errI) + (kD * errD) );

		if(avg >= lightThreshold && foundLine){
			//Start timer
			foundLine = false;
			clearTimer(T3);
		}

		if(!foundLine && time1(T3) >= 2000){
			followCmd.lSpeed = 0;
			followCmd.rSpeed = 0;
			sleep(100);
			followCmd.broadcasting = false;
		}

		if((avg <= ( setPt + setPtTolerance)) && (!foundLine)){
			followCmd.broadcasting = true;
			foundLine = true;
			wipeError();
		}
	}
}

task avoid(){
	while (true){

		if ((getUSDistance(leftSonar) < 10) || (getUSDistance(rightSonar) < 10) ){

      avoidCmd.broadcasting = true;
      avoidCmd.lSpeed = 0;
      avoidCmd.rSpeed = 0;

    }	else {

    	avoidCmd.broadcasting = false;

    }

	}
}

task calculateErrors(){

	dt = time1(T2);
	clearTimer(T2);

	errD = (errP - errPrev) / dt;
	errI += dt * errPrev;

	errPrev = errP;

	sleep(sampleLength);

}

void display(){
		string foll,fora,avo;
		if(followCmd.broadcasting){
			foll = "True";
		}
		else{
			foll = "False";
		}
		if(forageCmd.broadcasting){
			fora = "True";
		}
		else{
			fora = "False";
		}
		if(avoidCmd.broadcasting){
			avo = "True";
		}
		else{
			avo = "False";
		}
		displayTextLine(0, "Forage: %s, %f, %f", fora, forageCmd.lSpeed, forageCmd.rSpeed);
		displayTextLine(2, "Follow: %s, %f, %f", foll, followCmd.lSpeed, followCmd.rSpeed);
		displayTextLine(4, "Avoid: %s, %f, %f", avo, avoidCmd.lSpeed, avoidCmd.rSpeed);
		displayTextLine(6, "Average Colour: %i", avg);
}

task main(){

	startTask(calculateErrors);

	startTask(arbiter);
	startTask(forage);
	startTask(follow);
	startTask(avoid);

	while (true){
		display();
		//setMotorSpeed(leftMotor, leftSpeed);
		//setMotorSpeed(rightMotor, rightSpeed);

		bool datalogOK = datalogOpen(0,1, true);
		if(datalogOK){
			datalogAddLong(0,avg);
		}
		datalogClose();

	}
}
