#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     lightSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

bool foundLine = false;
long avg;
long maxLight, minLight;

long lightThreshold = 1100;

float errP, errI, errD, errPrev, maxCap, minCap;
long setPt = 500;
float setPtTolerance = 50;

//PID Coefficients
const float kP = 1.4;
const float kI = 0.000002;
const float kD = 0.5;

const float baseSpeed = 9;
float leftSpeed = 0;
float rightSpeed = 0;
float spiralFactor = 0.33;
float timeSinceLostLine = 0;

float dt = 0;
const float sampleLength = 50;

/* Timers
	T1: Object avoidance
	T2: PID rrror monitor
	T3: Track time since lost line
*/

//Command request struct for behaviours to request motor control
typedef struct {
	float lSpeed;
	float rSpeed;
	bool broadcasting;
	string name;
} cmdRequest;

cmdRequest followCmd;
cmdRequest forageCmd;
cmdRequest avoidCmd;
cmdRequest observeCmd;

void wipeError(){
	errP = 0;
	errI = 0;
	errD = 0;
}

void tryCmd(cmdRequest cmd){
	if(cmd.broadcasting){
		leftSpeed = cmd.lSpeed;
		rightSpeed = cmd.rSpeed;
		displayTextLine(8, cmd.name);
	}
}

long turnFixed(cmdRequest cmd, long angle, int dir){ //Turn by a fixed amount
	resetGyro(gyro);
	repeatUntil(getGyroDegrees(gyro) >= angle){
		cmd.lSpeed = 20 * dir;
		cmd.rSpeed = -20 * dir;
	}
	return getGyroDegrees(gyro);
}

task arbiter(){ //Behaviour arbitration
	while(true){
		tryCmd(forageCmd);
		tryCmd(followCmd);
		tryCmd(avoidCmd);
		//tryCmd(observeCmd);
		setMotorSpeed(leftMotor, leftSpeed);
		setMotorSpeed(rightMotor, rightSpeed);
	}
}

task forage(){
	forageCmd.name = "Forage";
	while(true){

		sleep(100);

		forageCmd.broadcasting = true;
		forageCmd.rSpeed = 30;

		if (leftSpeed < 30){
			forageCmd.lSpeed = leftSpeed + spiralFactor;
		}

	}
}

task follow() {

	followCmd.name = "Follow";
	clearTimer(T2);
	while(true){

		//HTCS2readRawRGB(S3, true, r,g,b);
		//avg = (0.3*r + 0.59*g + 0.11*b)/3;

		HTCS2readRawWhite(S3, true, avg);

		dt = time1(T2);
		clearTimer(T2);

		errD = (avg - errPrev) / dt;
		errI += dt * errPrev;
		errP = setPt - avg;

		errPrev = avg;
		if(errP < 0){
			followCmd.rSpeed = baseSpeed + maxCap * ( (kP * errP) + (kI * errI) + (kD * errD) );
			followCmd.lSpeed = baseSpeed - maxCap * ( (kP * errP) + (kI * errI) + (kD * errD) );
		}
		else if (errP >= 0){
			followCmd.rSpeed = baseSpeed + minCap * ( (kP * errP) + (kI * errI) + (kD * errD) );
			followCmd.lSpeed = baseSpeed - minCap * ( (kP * errP) + (kI * errI) + (kD * errD) );
		}

		if(kI * errI >= 20){
			errI = 0;
		}

		if(avg >= lightThreshold && foundLine){
			//Start timer
			foundLine = false;
			clearTimer(T3);
		}

		if(!foundLine && time1(T3) >= 2000){
			followCmd.lSpeed = 0;
			followCmd.rSpeed = 0;
			sleep(100);
			followCmd.broadcasting = false;
		}

		if((avg <= ( setPt + setPtTolerance)) && (!foundLine)){
			followCmd.broadcasting = true;
			foundLine = true;
			wipeError();
		}

		sleep(sampleLength);
	}
}

task avoid(){
	int turnCount = 0;
	avoidCmd.name = "Avoid";
	int i =0;
	while (true){

		long leftDist = getUSDistance(leftSonar);
		long rightDist = getUSDistance(rightSonar);

	  //detect object and start to reverse
	  if (leftDist < 20 || rightDist < 20 ){
	    avoidCmd.broadcasting = true;
	  }

	  if (leftDist < 10 || rightDist < 10){
	  	avoidCmd.broadcasting = true;
			repeatUntil(leftDist >= 20 && rightDist >=20){
				leftDist = getUSDistance(leftSonar);
				rightDist = getUSDistance(rightSonar);
				avoidCmd.lSpeed = -baseSpeed;
				avoidCmd.rSpeed = -baseSpeed;
			}
		}

		//Turn away from obstacle
	  if (avoidCmd.broadcasting && (leftDist <= 20 || rightDist <= 20)){
	 		repeatUntil(leftDist >= 20){
	  		clearTimer(T1);
	  		repeatUntil(time1(T1) >= 500){
	  			leftDist = getUSDistance(leftSonar);
					rightDist = getUSDistance(rightSonar);
	  			avoidCmd.lSpeed = baseSpeed;
					avoidCmd.rSpeed = -baseSpeed;
	  		}
	  		turnCount += 1;
	  	}
		}

		if (avoidCmd.broadcasting && leftDist > 20 && i <= 2000){
	  			avoidCmd.lSpeed = baseSpeed;
					avoidCmd.rSpeed = baseSpeed;
					i+=1;
		}
		//Try turning back round
		if (i >= 2000){
			avoidCmd.lSpeed = 0;
			avoidCmd.rSpeed = 0;
			i=0;
			clearTimer(T1);
			repeatUntil(time1(T1) >= turnCount * 1000){
	  			avoidCmd.lSpeed = -baseSpeed;
					avoidCmd.rSpeed = baseSpeed;
	  	}
	  	turnCount = 0;
	  	avoidCmd.lSpeed=baseSpeed;
	  	avoidCmd.rSpeed=baseSpeed;
		}

		if((avg <= ( setPt + setPtTolerance)) && (!foundLine) && avoidCmd.broadcasting){
				avoidCmd.broadcasting = false;
				foundLine = true;
				wipeError();
			}

		}
}

task calculateErrors(){

	dt = time1(T2);
	clearTimer(T2);

	errD = (errP - errPrev) / dt;
	errI += dt * errPrev;

	errPrev = errP;

	sleep(sampleLength);

}

void display(){
		//string foll,fora,avo;
		//if(followCmd.broadcasting){
		//	foll = "True";
		//}
		//else{
		//	foll = "False";
		//}
		//if(forageCmd.broadcasting){
		//	fora = "True";
		//}
		//else{
		//	fora = "False";
		//}
		//if(avoidCmd.broadcasting){
		//	avo = "True";
		//}
		//else{
		//	avo = "False";
		//}
		//displayTextLine(0, "Forage: %s, %f, %f", fora, forageCmd.lSpeed, forageCmd.rSpeed);
		//displayTextLine(2, "Follow: %s, %f, %f", foll, followCmd.lSpeed, followCmd.rSpeed);
		//displayTextLine(4, "Avoid: %s, %f, %f", avo, avoidCmd.lSpeed, avoidCmd.rSpeed);
		//displayTextLine(6, "Average Colour: %i", avg);
}

task main(){

	//startTask(calculateErrors);
	while(getButtonPress(buttonEnter)==0){
		displayTextLine(0, "Press for white");
	}

	HTCS2readRawWhite(S3, true, maxLight);
	sleep(500);

	while(getButtonPress(buttonEnter)==0){
		displayTextLine(0, "White: %f", maxLight);
		displayTextLine(2, "Press for Black");
	}

	HTCS2readRawWhite(S3, true, minLight);
	displayTextLine(2, "Black: %f", minLight);
	sleep(500);

	while(getButtonPress(buttonEnter)==0){
		displayTextLine(4, "Press for set point");
	}

	HTCS2readRawWhite(S3, true, setPt);
	displayTextLine(4, "Set pt: %f", setPt);
	sleep(500);

	lightThreshold = maxLight;
	//setPt = (black + white)/2;

	maxCap = baseSpeed/maxLight;
	minCap = baseSpeed/minLight;

	while(getButtonPress(buttonEnter)==0){
		displayTextLine(6, "Press to Start Robot");
	}

	sleep(200);

	startTask(arbiter);
	startTask(forage);
	startTask(follow);
	startTask(avoid);

	while (true){

		display();

	//	bool datalogOK = datalogOpen(0,4, true);
	//	if(datalogOK){
	//		datalogAddLong(0,avg);
	//		datalogAddFloat(1, leftSpeed);
	//		datalogAddFloat(2, rightSpeed);
			//datalogAddFloat(3, (leftSpeed + rightSpeed) / (leftSpeed * rightSpeed));
//		}
//		datalogClose();

	}
}
