#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     lightSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

bool foundLine = false;
long r,g,b,avg,avgCapped;

long lightThreshold = 2000;

float errP, errI, errD, errPrev;
float setPt = 460;
float setPtTolerance = 40;

//PID Coefficients
const float kP = 0.024;
const float kI = 0.014;
const float kD = 0.018;

const float baseSpeed = 12;
float leftSpeed = 0;
float rightSpeed = 0;
float spiralFactor = 0.5;
float timeSinceLostLine = 0;

float dt = 0;
const float sampleLength = 100;

/* Timers
	T1: Object avoidance
	T2: PID rrror monitor
	T3: Track time since lost line
*/

//Command request struct for behaviours to request motor control
typedef struct {
	float lSpeed;
	float rSpeed;
	bool broadcasting;
} cmdRequest;

cmdRequest followCmd;
cmdRequest forageCmd;
cmdRequest avoidCmd;
cmdRequest observeCmd;

void wipeError(){
	errP = 0;
	errI = 0;
	errD = 0;
}

void tryCmd(cmdRequest cmd){
	if(cmd.broadcasting){
		leftSpeed = cmd.lSpeed;
		rightSpeed = cmd.rSpeed;
	}
}

long turnFixed(cmdRequest cmd, long angle, int dir){ //Turn by a fixed amount
	resetGyro(gyro);
	repeatUntil(getGyroDegrees(gyro) >= angle){
		cmd.lSpeed = 20 * dir;
		cmd.rSpeed = -20 * dir;
	}
	return getGyroDegrees(gyro);
}

task arbiter(){ //Behaviour arbitration
	while(true){
		tryCmd(forageCmd);
		tryCmd(followCmd);
		//tryCmd(avoidCmd);
		//tryCmd(observeCmd);
		setMotorSpeed(leftMotor, leftSpeed);
		setMotorSpeed(rightMotor, rightSpeed);
	}
}

task forage(){
	while(true){

		sleep(100);

		forageCmd.broadcasting = true;
		forageCmd.rSpeed = 30;

		if (leftSpeed < 30){
			forageCmd.lSpeed = leftSpeed + spiralFactor;
		}

	}
}

task follow() {
	while(true){

		HTCS2readRawRGB(S3, true, r,g,b);
		avg = (r + g + b)/3;

		//if(avg >= 800){
		//	avgCapped=800;
		//}
		//else{
		//	avgCapped = avg;
		//}

		errP = setPt - avgCapped;

		followCmd.rSpeed = baseSpeed + ( (kP * errP) + (kI * errI) + (kD * errD) );
		followCmd.lSpeed = baseSpeed - ( (kP * errP) + (kI * errI) + (kD * errD) );

		if(avg >= lightThreshold && foundLine){
			//Start timer
			foundLine = false;
			clearTimer(T3);
		}

		if(!foundLine && time1(T3) >= 2000){
			followCmd.lSpeed = 0;
			followCmd.rSpeed = 0;
			sleep(100);
			followCmd.broadcasting = false;
		}

		if((avg <= ( setPt + setPtTolerance)) && (!foundLine) && !followCmd.broadcasting){
			followCmd.broadcasting = true;
			sleep(100);
			foundLine = true;
			wipeError();
		}
	}
}

//task avoid(){

//	bool avoiding = false;
//	avoidCmd.broadcasting = false;
//	long time = 0;

//	while (true){
//	}
//}


task tPropagator(){

	dt = time1(T2);
	clearTimer(T2);

	errD = (errP - errPrev) / dt;
	errI += dt * errPrev;

	errPrev = errP;

	sleep(sampleLength);

}

task main(){

	startTask(tPropagator);
	startTask(arbiter);
	startTask(forage);
	startTask(follow);
	//startTask(avoid);

	while (true){

		//setMotorSpeed(leftMotor, leftSpeed);
		//setMotorSpeed(rightMotor, rightSpeed);

		bool datalogOK = datalogOpen(0,1, true);
		if(datalogOK){
			datalogAddLong(0,avg);
		}
		datalogClose();

	}
}
