#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     lightSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

const long target = 450;
const long steeringMod = 0.02;
const long botSpeed = 5;

task main()
{
	startTask(followLine);
	
	while(true){}
}

task followLine()
{
	long r,g,b,avg,delta;;

	while(true){
		
		HTCS2readRawRGB(S3, true, r,g,b);
		avg = (r + g + b)/3;
		delta = target - avg;

		setMotorSpeed(leftMotor, botSpeed + (delta * steeringMod));
		setMotorSpeed(rightMotor, botSpeed - (delta * steeringMod));
		
	}
}