#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     lightSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

const long lightThreshold = 450;

int prevDirection = -1;

task main()
{
	startTask(findLine);
	startTask(driveStraight);
}

task driveStraight()
{
	long r,g,b;
	long lightMag;

	while(true){
		HTCS2readRawRGB(S3, true, r,g,b);
		lightMag = sqrt(r*r+g*g+b*b);

		while(lightMag < lightThreshold) {
			setMotorSpeed(leftMotor, 10);
			setMotorSpeed(rightMotor, 10);
		}
	}
}

task findLine()
{
	long r,g,b;
	long lightMag, prevMag, delta;
	
	while(true){
		
		prevMag = lightMag;
		HTCS2readRawRGB(S3, true, r,g,b);
		lightMag = sqrt(r*r+g*g+b*b);
		delta = lightMag - prevMag;
		
		if(delta > 0){
			prevDirection = prevDirection * -1;
		}
	
		while(lightMag > lightThreshold) {
		
			//Need to turn to find track
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
			
			//try turning in the previous direction:
			setMotorSpeed(leftMotor, 5*prevDirection);
			setMotorSpeed(rightMotor, -5*prevDirection);
			
		
		}
		
	}
}
