#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     lightSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

const long lightThreshold = 450;

task main()
{

}

task driveStraight()
{
	long r,g,b;
	long lightMag;

	while (true){
		HTCS2readRawRGB(S3, true, r,g,b);

		lightMag = sqrt(r*r+g*g+b*b);

		while (lightMag < lightThreshold) {
			setMotorSpeed(leftMotor, 10);
			setMotorSpeed(rightMotor, 10);
		}
	}
}

task findLine()
{
	
}