#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     lightSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

task testRight(){
	long r,g,b;

	HTCS2readRawRGB(S3, true, r,g,b);
	int Avg = (r+g+b)/3;

	while (Avg > 550){
		HTCS2readRawRGB(S3, true, r,g,b);
		int Avg = (r+g+b)/3;
	
		setMotorSpeed(leftMotor, 2.5);
		setMotorSpeed(rightMotor, -2.5);
		
		if (Avg >750){
			break;
		}
	}


}

task testLeft(){
	long r,g,b;

	HTCS2readRawRGB(S3, true, r,g,b);
	int Avg = (r+g+b)/3;

	while (Avg > 550){
		HTCS2readRawRGB(S3, true, r,g,b);
		int Avg = (r+g+b)/3;
	
		setMotorSpeed(leftMotor, -2.5);
		setMotorSpeed(rightMotor, 2.5);
		
		if (Avg >750){
			break;
		}
	}	
}

task main()
{
	long r,g,b;

	while (true){
		HTCS2readRawRGB(S3, true, r,g,b);


		int avg = (r+g+b)/3;

		 while (avg < 550) {
		  setMotorSpeed(leftMotor, 10);
			setMotorSpeed(rightMotor, 10);
		}
		
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);

		startTask(testRight);

		HTCS2readRawRGB(S3, true, r,g,b);
		avg = (r+g+b)/3;
		
		if (avg >750){
		startTask(testLeft);	
		}
		
		writeDebugStreamLine("%d ", avg);
		displayTextLine(1, "%d", avg);
}
}
