#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S2,     rightSonar,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     lightSensor,    sensorI2CCustom)
#pragma config(Sensor, S4,     leftSonar,      sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "HitechnicColorSensor.h"

bool foundLine = false;
long r,g,b;
long avg;
const edge = 450;

task main() {

  while (!foundLine){
      
      HTCS2readRawRGB(S3, true, r,g,b);
      avg = (r+g+b)/3;
      
      setMotorSpeed(leftMotor, 4);
      setMotorSpeed(rightMotor, 8);
   
      if (avg ==  edge){
        foundLine = true;
        setMotorSpeed(leftMotor, 0);
        setMotorSpeed(rightMotor, 0);
      }
     
  }
  
}
